### ISSUE TITLE
Support lizmap web client 3.3.0

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-mapbuilder-module#1]
In the mapBuilder module.xml file, it is defined that mapBuilder module depends on Lizmap-Web-Client version 3.2.* and is not compatible with version 3.3.*.

To fix it update line 13 of https://github.com/3liz/lizmap-mapbuilder-module/blob/master/mapBuilder/module.xml
```
-        <module name="lizmap" minversion="3.2.0" maxversion="3.2.*"/>
+        <module name="lizmap" minversion="3.2.0" maxversion="3.3.*"/>
```

**Comment by nboisteault** [comment]
Fix with https://github.com/3liz/lizmap-mapbuilder-module/commit/8115667b4d7873cf215e0acc5b418094a3621d67
