### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by sergiuspinheiro** [3liz/lizmap-mapbuilder-module#2]
Hello
I have the Portuguese translation of the application but I can't upload it because Uploads are disabled.
"File uploads require push access to this repository."
I am happy to collaborate with your project

[mapBuilder_portuguese.zip](https://github.com/3liz/lizmap-mapbuilder-module/files/3882828/mapBuilder_portuguese.zip)

greetings

**Comment by nboisteault** [comment]
@sergiuspinheiro your translation is very welcome. I add it to master and I'll add to a release soon Obrigado !
![image](https://user-images.githubusercontent.com/2145040/73445870-f9c8e900-435b-11ea-8e80-d3d43f2c60b3.png)
