### ISSUE TITLE
Use InkMap to enhance printing

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-mapbuilder-module#25]
Printing web maps is a challenge in terms of performance, precision and flexibility. InkMap aims to conquer this challenge on the front-end. As an open source Javascript library, it facilitates usage and provides fast results without limiting browser performance. Under the hood InkMap makes use of other open source libraries and modern web technologies.

https://github.com/camptocamp/inkmap

**Comment by neo-garaix** [comment]
Done in [Release 2.2.0](https://github.com/3liz/lizmap-mapbuilder-module/releases/tag/2.2.0)
