### ISSUE TITLE
Map Builder needs another version of Lizmap

### ISSUE THREAD

**Issue by ams96** [3liz/lizmap-mapbuilder-module#27]
I have Lizmap 3.4.5 and I tried to install MapBuilder 2.0.0 and 2.0.1 and every time I have this message when I launch the installer.php. 
[error] The module mapBuilder needs another version of the module lizmap (3.4.0 - 3.4.*)

Should I try with a less recent version of Lizmap ?

Thank you

**Comment by Gustry** [comment]
https://github.com/3liz/lizmap-mapbuilder-module/releases/tag/2.0.2 I haven't tested.

**Comment by Gustry** [comment]
I'm closing as this issue is old and it should be already fixed.
