### ISSUE TITLE
Launch file

### ISSUE THREAD

**Issue by Maverick83000** [3liz/lizmap-mapbuilder-module#3]
Hi.
I have a silly question:  In what file in the lizmap web client should I put the lizmap-mapbuilder-module-master file ?

Thanks for your answers !

**Comment by nboisteault** [comment]
`/lizmap/lizmap-modules/`

**Comment by nboisteault** [comment]
@Maverick83000 Did it work ?

**Comment by Maverick83000** [comment]
Hi,
I'm sorry for the late response but I don't try the manipulation to date. I tried now but it doesn't work.
I downloaded the module's zip, I putt and unzip it in the lizmap-modules folder.
I modified the localconfig file (var/config/localconfig.ini.php) and add the module:
_[modules]
lizmap.installparam=demo
mapBuilder.access=2
mapBuilderAdmin.access=2_

Then I execute the install :
_php lizmap/install/installer.php
lizmap/install/clean_vartmp.sh
lizmap/install/set_rights.sh_

But there is no file _mapBuilder.ini.php_ in _/var/config/_
And nothing in the Administration's panel
My lizmap version is the 3.3.6

Thanks for your help and good afternoon

**Comment by Maverick83000** [comment]
Maybe may I launch the _install.php_ file in the _mapBuilder_ and _mapBuilderAdmin_ folder ?

**Comment by nboisteault** [comment]
@Maverick83000 I can reproduce your issue, for some reason `mapBuilder.ini.php` is not copied in `/lizmap/var/config` when using an archive. But you can copy it from [here](https://github.com/3liz/lizmap-mapbuilder-module/blob/master/mapBuilder/install/conf/mapBuilder.ini.php) and it should works.

**Comment by Maverick83000** [comment]
Hi. 
Thank for your message.
I successfully installed the module.
For that, I don't put all the file _lizmap-mapbuilder-module-master_ into _lizmap-modules_ but I split it in two files : _mapBuilder_ and _mapBuilderAdmin_ and it works !
Really thank you

**Comment by Gustry** [comment]
@Maverick83000 Any thing to fix in the readme according to you? Or can we close?

**Comment by Maverick83000** [comment]
It's good for me!
Thanks for your help

**Comment by nboisteault** [comment]
@Maverick83000 thanks for your feedback!
