### ISSUE TITLE
Both the installation methods : Manual or via Composer don't work for me on Ubuntu 22.04, LWC 3.6 and PHP 7.4.33

### ISSUE THREAD

**Issue by Antoviscomi** [3liz/lizmap-mapbuilder-module#42]
1. via Composer
/var/www/lizmap/lizmap/lizmap-modules$ composer require --working-dir=/var/www/lizmap/lizmap/my-packages "var/www/lizmap/lizmap-mapbuilder-module=2.1.*"
PHP Parse error:  syntax error, unexpected '|', expecting variable (T_VARIABLE) in /usr/share/php/Composer/IO/BaseIO.php on line 163
Parse error: syntax error, unexpected '|', expecting variable (T_VARIABLE) in /usr/share/php/Composer/IO/BaseIO.php on line 163
-------------------------------------------------
2. manual installation 
/var/www/lizmap/lizmap/install$ php configure.php mapBuilder
PHP Fatal error:  Uncaught Error: Class 'Jelix\Installer\Module\Configurator' not found in /var/www/lizmap/lizmap/install/configure.php:17
Stack trace:
#0 {main}
  thrown in /var/www/lizmap/lizmap/install/configure.php on line 17

**Comment by nworr** [comment]
1. regarding the error, it seems composer is uncorrecty installed, (or incompatible php version ??)

2. looks like lizmap in not fully installed or in a previous version (3.5 ?)

**Comment by Antoviscomi** [comment]
@nworr 
1. my php version is 7.4.33
2. my LWC version It's 3.6
3. I purged composer and reinstall it (Composer version 2.5.1 2022-12-22 15:33:54), 
It download correctly the packages now but, 
when I move to _/lizmap/install_ and try to launch  the command _php configure php_ 
I still receive the same error message pasted here
_/lizmap/install$ php configure.php mapBuilder
PHP Fatal error:  Uncaught Error: Class 'Jelix\Installer\Module\Configurator' not found in /var/www/lizmap/lizmap/install/configure.php:17
Stack trace:
#0 {main}
  thrown in /var/www/lizmap/lizmap/install/configure.php on line 17_

so I think something else  went wrong

**Comment by nworr** [comment]
there's an error in the doc, can you try and launch 
` php configurator.php mapBuilder ` instead ?

**Comment by Antoviscomi** [comment]
@nworr BINGO!
thank you very much
I close this topic as solved (please update the documentation)

**Comment by Antoviscomi** [comment]
@nworr thanks a lot
